name: Upload Python Package to PyPI

on:
  release:
    types:
      - published  # Trigger on published releases

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Allow read access to the repository
      id-token: write # Required for OIDC authentication with PyPI
    steps:
      # Step 1: Checkout the repository code
      - uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies to build the package
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      # Step 4: Build the distribution (source and wheel)
      - name: Build the package
        run: python -m build

      # Step 5: Publish to PyPI using the PyPI trusted publisher OIDC authentication
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}  # Use the API token stored in GitHub Secrets
