name: Upload Python Package to PyPI

on:
  release:
    types: [published]  # Triggers on new release creation in GitHub

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you are using

      # Step 3: Install build tools (setuptools, wheel, and build)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      # Step 4: Build the distribution (source and wheel)
      - name: Build the package
        run: python -m build

      # Step 5: Publish to PyPI
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}  # Reference to PyPI API token stored in GitHub Secrets
